services:
  - type: web
    name: assigneval
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
